services:
  validator:
    build:
      context: ..
      dockerfile: validator/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/app        
      - ~/.bittensor/wallets:/root/.bittensor/wallets:ro
      - /var/log/bitrecs/validator:/var/log/bitrecs/validator
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1