services:
  validator:
    container_name: bitrecs-validator
    build:
      context: ..
      dockerfile: validator/Dockerfile
    volumes:
      - /app/.venv  # Exclude .venv from the mount
      - ../:/app
      - /var/run/docker.sock:/var/run/docker.sock    
      - ~/.bittensor/wallets:/root/.bittensor/wallets:ro
      - /var/log/bitrecs/validator:/var/log/bitrecs/validator      
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - bitrecs-network
    restart: unless-stopped

networks:
  bitrecs-network:
    external: false

watchtower:
  image: nickfedor/watchtower
  container_name: bitrecs-watchtower
  restart: unless-stopped
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: --interval 60 bitrecs-validator