services:
  validator:
    build:
      context: ..
      dockerfile: validator/Dockerfile
    volumes:
      - ../:/app
      - /app/.venv  # Exclude .venv from the mount
      - /var/run/docker.sock:/var/run/docker.sock    
      - ~/.bittensor/wallets:/root/.bittensor/wallets:ro
      - /var/log/bitrecs/validator:/var/log/bitrecs/validator
      
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - bitrecs-network

networks:
  bitrecs-network:
    external: false